name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base-jammy
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
          source install/setup.bash
          colcon test
          colcon test-result --all
